#!/usr/bin/env python3

import sys
import os
import nltk

from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():
    #ensure proper usasge
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen name")
        
    #remove the '@' from the screen name
    screen_name = sys.argv[1].strip("@")
    
    #get the user's previous tweets
    tweets = get_user_timeline(screen_name,50)
    
    #check if successful
    if tweets == None:
        sys.exit("Invalid Screen Name")
    
    #run analyzer
    score_tweets(tweets)

def score_tweets(tweets):
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    #iterate over each tweet
    for tweet in tweets:
        # analyze tweet
        score = analyzer.analyze(tweet)
        #print the score and the tweet in the specified format
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

if __name__=="__main__":
    main()

    
    
    
            
    
            
